### ISSUE TITLE
Unable to build linux_vita

### ISSUE THREAD

**Issue by Cinder4198** [xerpi/linux_vita#2]
Running Linux Mint 21.2 Cinnamon, Cinnamon Version 5.8.4, Linux Kernal 5.15.0-89-generic.
When I try to run 'make ARCH=arm vita_defconfig' it returns with this error:

```***
*** Can't find default configuration "arch/arm/configs/vita_defconfig"!
***
make[2]: *** [scripts/kconfig/Makefile:94: vita_defconfig] Error 1
make[1]: *** [/home/eyasu/linux_vita/Makefile:685: vita_defconfig] Error 2
make: *** [Makefile:234: __sub-make] Error 2
```

I'm not sure if the guide doc is outdated and I'm suppose to run a different command, or if the vita_defconfig file is just missing, but I did try downloading the one from the original master branch and then running it. It worked, but when running 'make ARCH=arm CROSS_COMPILE=arm-linux- -j' it returned this error as well:
```  SYNC    include/config/auto.conf.cmd
scripts/Kconfig.include:39: C compiler 'arm-linux-gcc' not found
make[3]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[2]: *** [Makefile:685: syncconfig] Error 2
make[1]: *** [/home/eyasu/linux_vita/Makefile:786: include/config/auto.conf.cmd] Error 2
make: *** [Makefile:234: __sub-make] Error 2
```

**Comment by xerpi** [comment]
Try with this branch: https://github.com/xerpi/linux_vita/tree/rebase-6.7.0-rc5

**Comment by Cinder4198** [comment]
`make ARCH=arm vita_defconfig` works on the new branch, but `make ARCH=arm CROSS_COMPILE=arm-linux- -j` still returns with the same error

**Comment by xerpi** [comment]
> `make ARCH=arm vita_defconfig` works on the new branch, but `make ARCH=arm CROSS_COMPILE=arm-linux- -j` still returns with the same error

It seems like your `$PATH` doesn't contain a directory with `arm-linux-gcc`. Have you installed the bootlin toolchain?

**Comment by Cinder4198** [comment]
My bad, seems like I forgot to run the last command when it came to installing bootlin.
I made sure to set it up correctly this time, it's returning a different error for `make ARCH=arm CROSS_COMPILE=arm-linux- -j`


`make[1]: *** [/home/eyasu/linux_vita/Makefile:1911: .] Error 2`
`make: *** [Makefile:234: __sub-make] Error 2`

**Comment by xerpi** [comment]
> My bad, seems like I forgot to run the last command when it came to installing bootlin. I made sure to set it up correctly this time, it's returning a different error for `make ARCH=arm CROSS_COMPILE=arm-linux- -j`
> 
> `make[1]: *** [/home/eyasu/linux_vita/Makefile:1911: .] Error 2` `make: *** [Makefile:234: __sub-make] Error 2`

Hmm this error doesn't tell much. Mind talking on Discord? My username is _xerpi_.

**Comment by Cinder4198** [comment]
For anyone having the same problem, the issue with the second command was stemming from it being configured to look for a 'rootfs.cpio.zst' file rather than a 'rootfs.cpio.zst' which is generated from buildroot.

It was fixed by configuring buildroot to generate a .zst file, which is done by:
1: run 'make menuconfig' in buildroot
2: navigate to 'Filesystem Image' then 'Compression Method' 
3: select zstd. 
4: run 'make -j' in buildroot, it should now generate 'rootfs.cpio.zst' instead of 'rootfs.cpio.xz' 
5: copy 'rootfs.cpio.zst' into the 'linux_vita' folder
6: build linux

You can also change the linux config to use .xz, but I don't know how to do that
